app/models.py
from app import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from . import login_manager

from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Permission:
    CREATE_MODEL = 1
    SEE_MODEL = 2
    CREATE_MANAGER = 4
    ADMINISTER = 64


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    permissions = db.Column(db.Integer)
    default = db.Column(db.Boolean, default=False, index=True)

    # Relations
    users = db.relationship('User', backref='role', lazy='dynamic')

    @staticmethod
    def insert_roles():
        roles = {
            'Manager': [Permission.CREATE_MODEL],
            'Administrator': [Permission.CREATE_MODEL, Permission.CREATE_MANAGER,
                              Permission.SEE_MODEL, Permission.ADMINISTER]
        }

        default_role = 'Administrator'
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role()
                role.name = r
            role.reset_permission()
            for perm in roles[r]:
                role.add_permission(perm)
            role.default = (role.name == default_role)
            db.session.add(role)
        db.session.commit()

    def add_permission(self, perm):
        if not self.has_permission(perm):
            self.permissions += perm

    def remove_permission(self, perm):
        if self.has_permission(perm):
            self.permissions -= perm

    def reset_permission(self):
        self.permissions = 0

    def has_permission(self, perm):
        return self.permissions & perm == perm


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    is_root = db.Column(db.Boolean, default=False)
    is_admin = db.Column(db.Boolean, default=False)

    # Relations
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    avatar_id = db.Column(db.Integer, db.ForeignKey('photos.id'))
    models = db.relationship('Model', backref='manager')
    archive = db.relationship('Contract', backref='manager', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


class Model(db.Model):
    __tablename__ = 'models'
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(140))
    date_of_birth = db.Column(db.Date)
    city = db.Column(db.String(64))
    phone = db.Column(db.String(14))
    departure_date = db.Column(db.Date)
    start_date = db.Column(db.Date)
    next_date = db.Column(db.Date)
    ticket_price = db.Column(db.Float)
    is_accepted_by_admin = db.Column(db.Boolean)
    is_accepted_by_root = db.Column(db.Boolean)
    period = db.Column(db.Integer)
    is_archived = db.Column(db.Boolean, default=False)
    height = db.Column(db.Float)
    weight = db.Column(db.Float)
    age = db.Column(db.Integer)

    # Relations
    manager_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    club_id = db.Column(db.Integer, db.ForeignKey('clubs.id'))
    avatar_id = db.Column(db.Integer)

    photos = db.relationship('Photo', backref='model', lazy='dynamic', uselist=True)
    contracts = db.relationship('Contract', backref='model', lazy='dynamic')

    @property
    def end_date(self):
        if self.start_date is not None and self.period is not None:
            delta = datetime.utcnow().date() - self.start_date
            if delta.days <= 0:
                self.is_archived = False
                return self.period
            elif (delta.days > 0) and (delta.days < self.period):
                self.is_archived = False
                return self.period - delta.days
            else:
                self.is_archived = True
                return 'В архиве'
        return '-'


class Club(db.Model):
    __tablename__ = 'clubs'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), unique=True)

    # Relations
    models = db.relationship('Model', backref='club')

    def __repr__(self):
        return self.name


class Photo(db.Model):
    __tablename__ = 'photos'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    url = db.Column(db.String(128))

    model_id = db.Column(db.Integer, db.ForeignKey('models.id'))


class Contract(db.Model):
    __tablename__ = 'contracts'
    id = db.Column(db.Integer, primary_key=True)
    start_date = db.Column(db.Date)
    work_period = db.Column(db.Integer)  # Period of work in days

    # Relations
    model_id = db.Column(db.Integer, db.ForeignKey('models.id'))
    club_id = db.Column(db.Integer, db.ForeignKey('clubs.id'))
    manager_id = db.Column(db.Integer, db.ForeignKey('users.id'))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, FileField, SubmitField, DateField, BooleanField
from wtforms.validators import DataRequired, Length


class AddManagerForm(FlaskForm):
    name = StringField('Имя менеджера', validators=[DataRequired(), Length(1, 64)])
    username = StringField('Никнейм', validators=[DataRequired(), Length(1, 64)])
    password = PasswordField('Пароль', validators=[DataRequired()])
    is_admin = BooleanField('Администратор', default=False)
    photo = FileField('Загрузить фото')
    submit = SubmitField('Добавить')


class AddModelForm(FlaskForm):
    full_name = StringField('ФИО', validators=[DataRequired(), Length(1, 140)])
    date_of_birth = DateField('Дата рождения', validators=[DataRequired()])
    city = StringField('Город', validators=[DataRequired(), Length(64)])
    phone = StringField('Телефон', validators=[Length(0, 14)])
    departure_date = DateField('Желаемая дата вылета')
    start_date = DateField('Дата начала работы')
    ticket_price = StringField('Цена билета')
    # club = SelectField('Клуб')
    # avatar = FileField('Загрузить аватар')
    # photos = MultipleFileField('Загрузить несколько фотографий')
    submit = SubmitField('Добавить')

    # def __init__(self, clubs=[]):
    #     self.club.choices = clubs


class AddClubForm(FlaskForm):
    name = StringField('Название клуба', validators=[DataRequired(), Length(1, 128)])
    submit = SubmitField('Добавить')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
import os
import zipfile

from flask import render_template, redirect, url_for, request, flash, send_file
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename

from . import main
from .forms import AddManagerForm, AddClubForm

from app import db
from app.models import User, Club, Model, Photo
from config import allowed_file, UPLOAD_FOLDER, STATIC_FOLDER

from datetime import datetime


@main.route('/')
@login_required
def index():
    managers = []
    models = []
    clubs = []
    if current_user.is_admin:
        managers = User.query.order_by(User.id.desc()).all()
        models = Model.query.order_by(Model.id.desc()).all().copy()
        clubs = Club.query.order_by(Club.id.desc()).all()
    else:
        models = Model.query.filter_by(manager_id=current_user.id).order_by(Model.id.desc()).all().copy()
        clubs = Club.query.order_by(Club.id.desc()).all()

    for model in models:
        if model.end_date == "В архиве":
            models.remove(model)

    return render_template('main.html', managers=managers,
                           models=models,
                           clubs=clubs,
                           Photo=Photo)


@main.route('/register_manager', methods=['get', 'post'])
@login_required
def register_manager():
    form = AddManagerForm()
    if form.validate_on_submit():
        # Get the form data
        name = form.name.data
        username = form.username.data
        password = form.password.data
        is_admin = bool(form.is_admin.data)

        # Try to find an existing manager
        manager = User.query.filter_by(username=username).first()
        # If there is no manager with the username then create a new one
        if manager is None:
            # Create a new manager
            manager = User()
            manager.name = name
            manager.username = username
            manager.password = password
            manager.is_admin = is_admin

            # Handle image uploading
            file = form.photo.data
            if file is not None:
                if type(file) != str:
                    if file.filename == '':
                        flash('Не выбран файл')
                        return redirect(request.url)

                    if file and allowed_file(file.filename):
                        filename = secure_filename(file.filename)
                        file_path = os.path.join(UPLOAD_FOLDER, filename)
                        file.save(file_path)

                        photo = Photo()
                        photo.name = filename
                        photo.url = file_path

                        db.session.add(photo)
                        db.session.commit()

                        manager.avatar_id = photo.id

            # Save him into the database
            db.session.add(manager)
            db.session.commit()

        return redirect(url_for('main.manager', id=manager.id))
    return render_template('register_manager.html', form=form)


@main.route('/edit_manager/<id>', methods=['get', 'post'])
def edit_manager(id):
    manager = User.query.filter_by(id=id).first()
    if request.method == 'POST':
        name = request.form['name']
        username = request.form['username']
        password = request.form['password']
        is_admin = request.form.get('is_admin')
        print(is_admin)

        if name != None and name != '':
            manager.name = name

        if username != None and username != '':
            manager.username = username

        if is_admin != '':
            manager.is_admin = bool(is_admin)

        if password != None and password != '':
            manager.password = password

            # Handle image uploading
        if 'file' in request.files:
            file = request.files['file']

            if file.filename == '':
                flash('Не выбран файл')
                return redirect(request.url)

            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file_path = os.path.join(UPLOAD_FOLDER, filename)
                file.save(file_path)

                photo = Photo()
                photo.name = filename
                photo.url = file_path

                db.session.add(photo)
                db.session.commit()

                manager.avatar_id = photo.id

        db.session.add(manager)
        db.session.commit()
        return redirect(url_for('main.manager', id=manager.id))

    return render_template('edit_manager.html', manager=manager)


@main.route('/delete_manager/<id>')
def delete_manager(id):
    manager = User.query.filter_by(id=id).first()
    db.session.delete(manager)
    db.session.commit()
    return redirect(url_for('main.index'))


@main.route('/create_model', methods=['get', 'post'])
@login_required
def create_model():
    errors = []
    clubs = Club.query.all()

    if request.method == 'POST':
        model = Model()

        # Required fields
        model.full_name = request.form['fullname']
        model.city = request.form['city']
        model.date_of_birth = datetime.strptime(request.form['date_of_birth'], '%d.%m.%Y').date()

        # Optional fields
        model.phone = request.form['phone']
        if request.form['start_date'] != '':
            model.start_date = datetime.strptime(request.form['start_date'], '%d.%m.%Y').date()
        if request.form['period'] != '':
            model.period = int(request.form['period'])
        if request.form['departure_date'] != '':
            model.departure_date = datetime.strptime(request.form['departure_date'], '%d.%m.%Y').date()

        if request.form['ticket_price'] != '':
            model.ticket_price = float(request.form['ticket_price'])
        if request.form['club'] != '':
            model.club_id = int(request.form['club'])
        model.manager_id = current_user.id

        # Handle image uploading
        if 'file' in request.files:
            file = request.files['file']

            if file.filename == '':
                flash('Не выбран файл')
                return redirect(request.url)

            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file_path = os.path.join(UPLOAD_FOLDER, filename)
                file.save(file_path)

                photo = Photo()
                photo.name = filename
                photo.url = file_path

                db.session.add(photo)
                db.session.commit()

                model.avatar_id = photo.id

        db.session.add(model)
        db.session.commit()

        return redirect(url_for('main.model', id=model.id))
    return render_template('create_model.html', clubs=clubs, errors=errors)


@main.route('/edit_model/<id>', methods=['get', 'post'])
def edit_model(id):
    if request.method == 'GET':
        model = Model.query.filter_by(id=id).first()
        clubs = Club.query.all()
    elif request.method == 'POST':
        model = Model.query.filter_by(id=id).first()
        # Required fields
        model.full_name = request.form['fullname']
        model.city = request.form['city']
        model.date_of_birth = datetime.strptime(request.form['date_of_birth'], '%d.%m.%Y').date()

        # Optional fields
        model.phone = request.form['phone']
        if request.form['start_date'] != '':
            model.start_date = datetime.strptime(request.form['start_date'], '%d.%m.%Y').date()
        if request.form['period'] != '':
            model.period = int(request.form['period'])
        if request.form['departure_date'] != '':
            model.departure_date = datetime.strptime(request.form['departure_date'], '%d.%m.%Y').date()
        if request.form['ticket_price'] != '':
            model.ticket_price = float(request.form['ticket_price'])
        if request.form['club'] != '':
            model.club_id = int(request.form['club'])
        if request.form['height'] != '':
            model.height = float(request.form['height'])
        if request.form['weight'] != '':
            model.weight = float(request.form['weight'])
        if request.form['age'] != '':
            model.age = int(request.form['age'])

        if 'is_accepted_by_root' in request.form:
            if request.form['is_accepted_by_root'] == 'True':
                model.is_accepted_by_root = True
            elif request.form['is_accepted_by_root'] == 'False':
                model.is_accepted_by_root = False

        if 'is_accepted_by_admin' in request.form:
            if request.form['is_accepted_by_admin'] == 'True':
                model.is_accepted_by_admin = True
            elif request.form['is_accepted_by_admin'] == 'False':
                model.is_accepted_by_admin = False

        if model.is_accepted_by_admin is not None and model.is_accepted_by_root is not None and \
                not model.is_accepted_by_root and not model.is_accepted_by_admin:
            avatar = Photo.query.filter_by(id=model.avatar_id).first()
            if avatar is not None:
                db.session.delete(avatar)
            db.session.delete(model)
            db.session.commit()
            print('model has been deleted')
            return redirect(url_for('main.index'))

        db.session.commit()
        return redirect(url_for('main.model', id=model.id))
    return render_template('edit_model.html', model=model, clubs=clubs)


@main.route('/add_photos/<id>', methods=['get', 'post'])
def add_photos(id):
    if request.method == 'POST':
        model = Model.query.filter_by(id=id).first()
        files = dict(request.files)
        if 'photos' in files:
            photos = files['photos']
            for photo in photos:
                print(photo)
                print(photo.filename)
                print(allowed_file(photo.filename))
                if photo != None and photo.filename != '' and allowed_file(photo.filename):

app/templates/add_photos.html
{% extends 'base.html' %}

{% block title %}
Загрузка фото в галерею
{% endblock %}

{% block content %}
  <div class="head">
  <h2>Загрузить фото в галерею</h2>
  </div>
  <div class="login-form">
    <form action="" enctype="multipart/form-data" method="post">
      <label for="photos">Выберите фотографии</label>
      <input type="file" multiple="multiple" id="photos" name="photos">
      <input type="submit" value="Загрузить фотографии" id="submit">
    </form>
  </div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav>
  {% block nav %}
    <ul>
      <li class="nav-item"><a href="{{ url_for('main.index') }}" id="logo">Korea Center</a></li>
      <li class="nav-item"><a href="{{ url_for('main.create_model') }}" id="add-item">Добавить модель</a></li>
      {% if current_user.is_root %}
        <li class="nav-item"><a href="{{ url_for('main.register_manager') }}" id="add-item">Добавить менеджера</a></li>
      {% endif %}
      {% if current_user.is_root or current_user.is_admin %}
        <li class="nav-item"><a href="{{ url_for('main.create_club') }}" id="add-item">Добавить клуб</a></li>
      {% endif %}

      {% if current_user.is_authenticated %}
        <li style="float:right; margin-top:26px;" class="nav-item"><a href="{{ url_for('auth.logout') }}">Выйти</a></li>
        <li style="float: right;" class="nav-item">
          <a href="{{ url_for('main.manager', id=current_user.id) }}"><strong class="my-profile">Мой <br>
            профиль</strong></a>
        </li>
      {% else %}
        <li style="float:right; margin-top:26px;" class="nav-item"><a href="{{ url_for('auth.logout') }}">Войти</a></li>
        <li style="float: right;" class="nav-item"><p>Пользователь неавторизован</p></li>
      {% endif %}
    </ul>
  {% endblock %}
</nav>
<div class="content">
  {% block content %}{% endblock %}
</div>
{% block footer %}
  {% include 'auth/_auth_footer.html' %}
{% endblock %}
</body>
</html>

app/templates/create_club.html
{% extends 'base.html' %}

{% block title %}Добавить клуб{% endblock %}

{% block content %}
  <h2>Новый клуб</h2>
  {% if current_user.is_admin %}
    <div class="login-form">
      <form action="{{ url_for('main.create_club') }}" method="post">
        {{ form.hidden_tag() }}
        <p>
          {{ form.name.label }}<br>
          {{ form.name(size=64) }}
        </p>
        <p>
          {{ form.submit() }}
        </p>
      </form>
    </div>
  {% else %}
    <p class="error">Создавать клубы могут только администраторы</p>
  {% endif %}

{% endblock %}

{% block footer %}
  {% include "auth/_auth_footer.html" %}
{% endblock %}

app/templates/create_model.html
{% extends 'base.html' %}

{% block title %}Добавить модель{% endblock %}


{% block content %}
  <h2>Новая модель</h2>

  <div class="model-form">
    <form action="{{ url_for('main.create_model') }}" method="post" enctype="multipart/form-data">

      <p>
        <label for="fullname">ФИО</label><br>
        <input type="text" name="fullname" placeholder="Иванова Алина Алексеевна" required>

      <p>
        <label for="date_of_birth">Дата рождения</label><br>
        <input type="text" name="date_of_birth" placeholder="01.01.1996" required>

      <p>
        <label for="city">Город</label><br>
        <input type="text" name="city" placeholder="Москва" required>

      <p>
        <label for="phone">Номер телефона</label><br>
        <input type="text" name="phone" placeholder="+79112345678">

      <p>
        <label for="departure_date">Желаемая дата вылета</label><br>
        <input type="text" name="departure_date" placeholder="01.01.2019">

      <p>
        <label for="ticket_price">Цена билета</label><br>
        <input type="text" name="ticket_price" placeholder="3500">

      <p>
        <label for="start_date">Дата начала работы</label><br>
        <input type="text" name="start_date" placeholder="01.01.2019">

      <p>
        <label for="period">Срок работы</label><br>
        <select name="period" id="period">
          <option value="30">30 дней</option>
          <option value="60">60 дней</option>
        </select>

      <p>
        <label for="club">Клуб</label><br>
        <select name="club" id="club">
          {% for club in clubs %}
            <option value="{{ club.id }}">{{ club.name }}</option>
          {% endfor %}
        </select>

      <p>
        <label for="file">Загрузить фото</label><br>
        <input type="file" name="file" id="file">

        <input type="submit" value="Добавить" id="submit">
    </form>
  </div>
{% endblock %}

{#{% block footer %}#}
{#  {% include "auth/_auth_footer.html" %}#}
{#{% endblock %}#}

app/templates/edit_club.html
{% extends 'base.html' %}

{% block title %}Редактировать клуб{% endblock %}

{% block content %}
  <div class="head">
    <h2>Редактировать клуб</h2>
    <a href="{{ url_for('main.delete_club', id=club.id) }}" class="delete-btn">Удалить клуб</a>
  </div>

  {% if current_user.is_admin %}
    <div class="login-form">
      <form action="{{ url_for('main.edit_club', id=club.id) }}" method="post">
        <p>
          <label for="name">Название</label><br>
          <input type="text" name="name" id="name" size="64" value="{{ club.name }}">
        </p>
        <p>
          <input type="submit" id="submit" value="Сохранить">
        </p>
      </form>
    </div>
  {% else %}
    <p class="error">Редактировать клубы могут только администраторы</p>
  {% endif %}
{% endblock %}

{% block footer %}
  {% include "auth/_auth_footer.html" %}
{% endblock %}

app/templates/edit_manager.html
{% extends 'base.html' %}

{% block title %}
  Редактировать менеджера
{% endblock %}

{% block content %}
  <div class="head">
    <h2>Редактировать менеджера</h2>
    {% if current_user.is_root and current_user.id != manager.id %}
      <a href="{{ url_for('main.delete_manager', id=manager.id) }}" class="delete-btn">Удалить менеджера</a>
    {% endif %}
  </div>

  <div class="login-form">
    <form action="" method="post" enctype="multipart/form-data">
      <p>
        <label for="name">Имя менеджера</label>
        <input type="text" name="name" id="name" size="64"
               value="{% if manager.name != none %}{{ manager.name }} {% endif %}">

      <p>
        <label for="username">Никнейм</label>
        <input type="text" name="username" id="username" size="64" value="{{ manager.username }}">

      <p>
        <label for="password">Пароль</label>
        <input type="password" name="password" id="password" size="64">

      <p>
        <input type="checkbox" name="is_admin" {% if manager.is_admin %}checked{% endif %} id="is_admin" value="y">
        <label for="is_admin"> Администратор</label>

      <p>
        <label for="file">Изменить фото</label><br>
        <input type="file" name="file" id="file">

      <p>
        <input type="submit" value="Сохранить изменения" id="submit">

    </form>
  </div>
{% endblock %}

app/templates/manager.html
{% extends 'base.html' %}

{% block title %}Менеджер {{ manager.username }} {% endblock %}

{% block content %}
  <div class="head">
    <h2>
      {% if manager.is_admin %}
        Администратор
      {% else %}
        Менеджер
      {% endif %}
      {{ manager.username }}
    </h2>
    {% if current_user.is_root %}
      <a href="{{ url_for('main.delete_manager', id=manager.id) }}" class="delete-btn">Удалить менеджера</a>
      <a href="{{ url_for('main.edit_manager', id=manager.id) }}" class="edit">Редактировать</a>
    {% endif %}
  </div>

  <!-- Manager's Info -->
  <div class="manager-profile">
    {% if avatar_filename != None %}
      <div class="avatar">
        <img src="{{ url_for('static', filename='images/{}'.format(avatar_filename)) }}" alt="" class="avatar">
      </div>
    {% endif %}

    <!-- Model List -->
    <div class="model-list">
      <h3>Всего моделей: {{ models|length }}</h3>
      {% if models|length > 0 %}
        <table style="text-align: center;">
          <tr class="table-head">
            <td style="width: 100px;text-align: center;">Фото</td>
            <td style="text-align: left;">Модель</td>
            <td>Начало работы</td>
            <td>Осталось <br> работать</td>
          </tr>
          {% for model in models %}
            {% if not model.is_archived %}
              <tr>
                <td style="width: 100px;">
                  <p style="text-align: center;">
                    <img style="border-radius: 3px;"
                         src="{{ url_for('static', filename=('images/' + Photo.query.filter_by(id=model.avatar_id).first().name)) }}"
                         class="model-list-avatar"
                    />
                  </p>
                </td>
                <td style="text-align: left;"><a
                    href="{{ url_for('main.model', id=model.id) }}">{{ model.full_name }}</a></td>
                {% if model.start_date is not none %}
                  <td>{{ model.start_date.strftime('%d.%m.%Y') }}</td>
                {% else %}
                  <td>Дата не указана</td>
                {% endif %}
                <td>{{ model.end_date }} дней</td>
              </tr>
            {% endif %}
          {% endfor %}
        </table>
        </div>
      {% endif %}

    <!-- Model Archive -->
    {% if models_archive|length > 0 %}
      <div class="models-archive">
        <h2>Архив моделей</h2>
        <table>
          <tr class="table-head">
            <td>Фамилия Имя Отчество</td>
            <td>Клуб</td>
            {# <td>Новый срок</td> #}
          </tr>
          {% for model in models_archive %}
            <tr>
              <td><a href="{{ url_for('main.model', id=model.id) }}">{{ model.full_name }}</a></td>
              <td><a href="{{ url_for('main.club', id=model.club.id) }}">{{ model.club.name }}</a></td>
              {# <td>{{ model.next_date }}</td> #}
            </tr>
          {% endfor %}
        </table>
      </div>
    {% endif %}
  </div>
{% endblock %}

app/templates/model.html
{% extends 'base.html' %}

{% block title %}Модель {{ model.full_name }}{% endblock %}

{% block content %}
  <div class="head">
    <h2>
      {{ model.full_name }} <br>
      {% if ((model.is_accepted_by_admin is not none) and model.is_accepted_by_admin)
      or ((model.is_accepted_by_root is not none) and model.is_accepted_by_root) %}
        (Одобрена)
      {% elif (model.is_accepted_by_admin is none) and (model.is_accepted_by_root is none) %}
        (Ожидает одобрения)
      {% else %}
        (Не одобрена)
      {% endif %}
    </h2>
    <a href="{{ url_for('main.delete_model', id=model.id) }}" class="delete-btn">Удалить модель</a>
    <a href="{{ url_for('main.edit_model', id=model.id) }}" class="edit">Редактировать</a>
  </div>

  <div class="model-profile">
    {% if avatar_filename != None %}
      <div class="avatar">
        <img src="{{ url_for('static', filename='images/{}'.format(avatar_filename)) }}" alt="" class="avatar">
      </div>
    {% endif %}
    <div class="model-info">
      <table>
        <tr>
          <td>ФИО</td>
          <td>{{ model.full_name }}</td>
        </tr>
        {% if model.height is not none %}
          <tr>
            <td>Рост</td>
            <td>{{ model.height }} см</td>
          </tr>
        {% endif %}
        {% if model.weight is not none %}
          <tr>
            <td>Вес</td>
            <td>{{ model.weight }} кг</td>
          </tr>
        {% endif %}
        {% if model.age is not none %}
          <tr>
            <td>Возраст</td>
            <td>{{ model.age }} лет</td>
          </tr>
        {% endif %}
        <tr>
          <td>Дата рождения</td>
          <td>{{ model.date_of_birth.strftime('%d.%m.%Y') }}</td>
        </tr>
        <tr>
          <td>Город</td>
          <td>{{ model.city }}</td>
        </tr>
        <tr>
          <td>Номер телефона</td>
          {% if model.phone == '' %}
            <td>Не указан</td>
          {% else %}
            <td>{{ model.phone }}</td>
          {% endif %}
        </tr>
        <tr>
          <td>Дата начала работы</td>
          {% if model.start_date is not none %}
            <td>{{ model.start_date.strftime('%d.%m.%Y') }}</td>
          {% else %}
            <td>Не указана</td>
          {% endif %}
        </tr>
        <tr>
          <td>Желаемая дата вылета</td>
          {% if model.departure_date is not none %}
            <td>{{ model.departure_date.strftime('%d.%m.%Y') }}</td>
          {% else %}
            <td>Не указана</td>
          {% endif %}
        </tr>
        <tr>
          <td>Цена билета</td>
          {% if model.ticket_price is not none %}
            <td>{{ model.ticket_price }}</td>
          {% else %}
            <td>Не указана</td>
          {% endif %}
        </tr>
        <tr>
          <td>Клуб</td>
          <td><a href="{{ url_for('main.club', id=model.club.id) }}">{{ model.club.name }}</a></td>
        </tr>
        <tr>
          <td>Менеджер</td>
          <td><a href="{{ url_for('main.manager', id=model.manager.id) }}">
            {% if model.manager.name == None %}
              {{ model.manager.username }}
            {% else %}
              {{ model.manager.name }}
            {% endif %}
          </a></td>
        </tr>
      </table>
    </div>
    {% if model.photos %}
      <div class="gallery">
        <div class="head">
          <h2>Галерея</h2>
          <a href="{{ url_for('main.add_photos', id=model.id) }}" class="edit">Добавить фото</a>
          <a href="{{ url_for('main.download_gallery', id=model.id) }}" class="edit">Скачать галлерею</a>
        </div>
        <div class="photo-list">
          {% for photo in model.photos %}
            <img src="{{ url_for('static', filename='images/{}'.format(photo.name)) }}" alt="" class="gallery-photo">
          {% endfor %}
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}